### ISSUE TITLE
The 'Pods-App' target has frameworks conflicting names: brlmprinterkit.framework.

### ISSUE THREAD

**Issue by kieranbarlow** [AbobosSoftware/cordova-plugin-brother-label-printer#51]
Trying to use this plugin in a CapacitorJs project, 

**Environment:**

- MacOS Monterey
- Intel Core i5
- Xcode v13.3.1

**Steps to reproduce:**

```
npm install cordova-plugin-brother-label-printer
npx cap sync
```

**Error**
`The 'Pods-App' target has frameworks with conflicting names: brlmprinterkit.framework.`

**Comment by arcadius** [comment]
Hello @kieranbarlow .
Thanks for reporting this issue.
It may not be very specific to this plugin.
Many entries come when you Google for `The 'Pods-App' target has frameworks with conflicting names`

**Comment by kieranbarlow** [comment]
Ok I'll raise the issue with Capacitor - might be worth keeping this open until I find out more because more and more are using CapacitorJs over Cordova.

**Comment by arcadius** [comment]
Hello @kieranbarlow 
Yesterday, I had this same issue and I was not able to build my project for iOS.
The new version 1.7.0 has just been released and it works now with Capacitor 4

Thanks for reporting this.
